
[[constraint]]
  name = "github.com/davecgh/go-spew"
  revision = "782f4967f2dc4564575ca782fe2d04090b5faca8"

[[constraint]]
  name = "github.com/docker/spdystream"
  revision = "449fdfce4d962303d702fec724ef0ad181c92528"

[[constraint]]
  name = "github.com/elazarl/goproxy"
  revision = "c4fc26588b6ef8af07a191fcb6476387bdd46711"

[[constraint]]
  name = "github.com/evanphx/json-patch"
  revision = "944e07253867aacae43c04b2e6a239005443f33a"

[[constraint]]
  name = "github.com/ghodss/yaml"
  revision = "73d445a93680fa1a78ae23a5839bad48f32ba1ee"

[[constraint]]
  name = "github.com/gogo/protobuf"
  revision = "c0656edd0d9eab7c66d1eb0c568f9039345796f7"

[[constraint]]
  name = "github.com/golang/glog"
  revision = "44145f04b68cf362d9c4df2182967c2275eaefed"

[[constraint]]
  name = "github.com/golang/groupcache"
  revision = "02826c3e79038b59d737d3b1c0a1d937f71a4433"

[[constraint]]
  name = "github.com/golang/protobuf"
  revision = "1643683e1b54a9e88ad26d98f81400c8c9d9f4f9"

[[constraint]]
  name = "github.com/google/gofuzz"
  revision = "44d81051d367757e1c7c6a5a86423ece9afcf63c"

[[constraint]]
  name = "github.com/googleapis/gnostic"
  revision = "0c5108395e2debce0d731cf0287ddf7242066aba"

[[constraint]]
  name = "github.com/hashicorp/golang-lru"
  revision = "a0d98a5f288019575c6d1f4bb1573fef2d1fcdc4"

[[constraint]]
  name = "github.com/json-iterator/go"
  revision = "13f86432b882000a51c6e610c620974462691a97"

[[constraint]]
  name = "github.com/mxk/go-flowrate"
  revision = "cca7078d478f8520f85629ad7c68962d31ed7682"

[[constraint]]
  name = "github.com/pborman/uuid"
  revision = "ca53cad383cad2479bbba7f7a1a05797ec1386e4"

[[constraint]]
  name = "github.com/pmezard/go-difflib"
  revision = "d8ed2627bdf02c080bf22230dbb337003b7aba2d"

[[constraint]]
  name = "github.com/spf13/pflag"
  revision = "4c012f6dcd9546820e378d0bdda4d8fc772cdfea"

[[constraint]]
  name = "github.com/stretchr/testify"
  revision = "f6abca593680b2315d2075e0f5e2a9751e3f431a"

[[constraint]]
  name = "golang.org/x/net"
  revision = "1c05540f6879653db88113bc4a2b70aec4bd491f"

[[constraint]]
  name = "golang.org/x/text"
  revision = "b19bf474d317b857955b12035d2c5acb57ce8b01"

[[constraint]]
  name = "gopkg.in/inf.v0"
  revision = "3887ee99ecf07df5b447e9b00d9c0b2adaa9f3e4"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  revision = "670d4cfef0544295bc27a114dbac37980d83185a"

[[constraint]]
  name = "k8s.io/kube-openapi"
  revision = "50ae88d24ede7b8bad68e23c805b5d3da5c8abaf"
